In [3]:
import os
import numpy as np 
import pickle 
from sklearn.utils.class_weight import compute_class_weight

In [4]:
ROOT_PATH = 'C:/Users/mingy/Documents/ml_data/bengali'

In [6]:
all_data = pickle.load(open(os.path.join(ROOT_PATH, 'all_data.p'),'rb'))

In [7]:
labels = np.array([x[1] for x in all_data])

In [8]:
grapheme_labels =labels[:, 0]
vowel_labels =labels[:, 1]
consonant_labels =labels[:, 2]

In [9]:
consonant_weights = np.clip(compute_class_weight('balanced', list(range(np.max(consonant_labels)+1)), consonant_labels), 0.5, 3)
consonant_weights

array([0.5       , 3.        , 1.22273295, 3.        , 1.34891531,
       1.34090894, 3.        ])

In [10]:
vowel_weights = np.clip(compute_class_weight('balanced', list(range(np.max(vowel_labels)+1)), vowel_labels), 0.5, 3)
vowel_weights

array([0.5       , 0.5       , 0.7031302 , 1.13039759, 0.96870659,
       3.        , 3.        , 0.63566417, 3.        , 1.13885865,
       3.        ])

In [11]:
grapheme_weights = np.clip(compute_class_weight('balanced', list(range(np.max(grapheme_labels)+1)), grapheme_labels), 0.5, 3)
grapheme_weights

array([3.        , 3.        , 3.        , 3.        , 3.        ,
       3.        , 3.        , 3.        , 3.        , 2.69251394,
       3.        , 3.        , 3.        , 0.5       , 1.50185451,
       1.10385613, 1.27178318, 1.57092798, 0.7320736 , 3.        ,
       3.        , 1.269083  , 0.5       , 0.5       , 3.        ,
       1.06075971, 3.        , 3.        , 1.57506744, 0.5       ,
       2.73564346, 1.55660962, 1.06075971, 3.        , 3.        ,
       2.5115046 , 1.16745722, 3.        , 0.5       , 1.93756271,
       1.57922879, 3.        , 0.61087184, 0.5       , 1.13100869,
       3.        , 2.06116585, 2.64485883, 0.86880537, 3.        ,
       1.61988644, 3.        , 1.27858416, 0.5       , 2.01938546,
       0.71159297, 0.5       , 1.88858798, 0.93033167, 0.51110568,
       2.80628214, 2.07908903, 1.37727672, 3.        , 0.5       ,
       0.87580673, 1.52096207, 2.51679198, 1.89457399, 1.57922879,
       1.24919142, 0.5       , 0.5       , 3.        , 0.78753

In [16]:
weights  = {
    'grapheme': grapheme_weights,
    'vowel': vowel_weights,
    'consonant': consonant_weights
}

In [17]:
pickle.dump(weights, open(os.path.join(ROOT_PATH, 'labels_weights.p'),'wb'))

In [15]:
os.path.join(ROOT_PATH, 'labels_weights.p')

'C:/Users/mingy/Documents/ml_data/bengali\\labels_weights.p'