16G RAM required to run this 

In [15]:
import os 
import pickle
import random
import numpy as np 
import pandas as pd
import sys
from pathlib import Path
sys.path.append('../')

In [4]:
from src.data.make_dataset import load_images, load_labels, dump_image_labels, split_train_test

In [7]:
dump_image_labels('train', ['0'])

Loading C:\Users\nasty\data-science\kaggle\bengali\data\raw\train_image_data_0.parquet


[(array([[254, 253, 252, ..., 254, 253, 251],
         [255, 253, 253, ..., 254, 253, 252],
         [255, 255, 255, ..., 254, 254, 253],
         ...,
         [254, 254, 253, ..., 253, 254, 252],
         [254, 254, 254, ..., 253, 253, 252],
         [254, 254, 254, ..., 253, 253, 251]], dtype=uint8),
  array([15,  9,  5], dtype=int64)),
 (array([[251, 244, 238, ..., 255, 255, 255],
         [252, 252, 250, ..., 255, 255, 255],
         [248, 248, 250, ..., 255, 255, 255],
         ...,
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 254],
         [255, 255, 255, ..., 255, 255, 254]], dtype=uint8),
  array([159,   0,   0], dtype=int64)),
 (array([[251, 250, 249, ..., 253, 253, 253],
         [252, 252, 252, ..., 253, 253, 253],
         [252, 253, 254, ..., 252, 253, 253],
         ...,
         [253, 253, 252, ..., 255, 254, 252],
         [252, 252, 252, ..., 254, 253, 250],
         [253, 252, 251, ..., 253, 251, 249]], dtype=uint8),
  array(

In [2]:
ROOT_FOLDER = 'C:/Users/nasty/data-science/kaggle/bengali/data'
TRAIN_PARQUET_FORM = 'train_image_data_ID.parquet'
TEST_PARQUET_FORM = 'test_image_data_ID.parquet'
LABEL_PATH = 'train.csv'

DEFAULT_H, DEFAULT_W = 137, 236


In [3]:
def load_images(train_test):
    path_form = {
        'train': TRAIN_PARQUET_FORM,
        'test': TEST_PARQUET_FORM
    }[train_test]
    imgs_list = [] 
    for id in ['0','1','2','3']:
        path = os.path.join(ROOT_FOLDER, path_form.replace('ID', id))
        print('Loading', path)
        df = pd.read_parquet(path)
        imgs = df.iloc[:, 1:].to_numpy()
        imgs_list.append(imgs)
        
    imgs_list = np.concatenate(imgs_list)
    imgs_list = imgs_list.reshape(-1, DEFAULT_H, DEFAULT_W)
    
    return imgs_list 

In [10]:
imgs = load_images('test')

Loading C:/Users/nasty/data-science/kaggle/bengali/data\test_image_data_0.parquet
Loading C:/Users/nasty/data-science/kaggle/bengali/data\test_image_data_1.parquet
Loading C:/Users/nasty/data-science/kaggle/bengali/data\test_image_data_2.parquet
Loading C:/Users/nasty/data-science/kaggle/bengali/data\test_image_data_3.parquet


In [14]:
pickle.dump(imgs, open(os.path.join(ROOT_FOLDER, 'test_data.p'), 'wb'))

In [ ]:
# test images
all_test_data = list()

In [5]:
labels = pd.read_csv(os.path.join(ROOT_FOLDER, LABEL_PATH))
labels = labels.iloc[:,1:4].to_numpy()
all_data = list(zip(imgs, labels))

In [6]:
pickle.dump(all_data, open(os.path.join(ROOT_FOLDER, 'all_data.p'),'wb'))

In [7]:
_ = random.shuffle(all_data)

In [8]:
data_size = len(all_data)
train_size = int(data_size *0.8)
train_data = all_data[:train_size]
val_data = all_data[train_size:]

In [9]:
pickle.dump(train_data, open(os.path.join(ROOT_FOLDER, 'train_data.p'),'wb'))
pickle.dump(val_data, open(os.path.join(ROOT_FOLDER, 'val_data.p'),'wb'))

## Train and validation sample data for testing

In [16]:
sample_train_path = 'C:/Users/nasty/data-science/kaggle/bengali/data/interim/train_data_0.p'
PATH_DATA_INTERIM = Path('C:/Users/nasty/data-science/kaggle/bengali/data/interim/')

In [12]:
train_imgs = pickle.load(open(sample_train_path, 'rb'))

In [17]:
def split_train_test(train_imgs):
    data_size = len(imgs)
    train_size = int(data_size * 0.8)
    train_data = train_imgs[:train_size]
    val_data = train_imgs[train_size:]
    pickle.dump(train_data, open(PATH_DATA_INTERIM / 'train_data_sample.p', 'wb'))
    pickle.dump(val_data, open(PATH_DATA_INTERIM / 'val_data_sample.p', 'wb'))
    
split_train_test(train_imgs)